### ISSUE TITLE
[Feature Request] Could shortcut added to enter specific POD container

### ISSUE THREAD

**Issue by hiberabyss** [c9s/vikube.vim#10]
Could shortcut like `e` added to enter specific POD container shell?

Thanks!

**Comment by c9s** [comment]
Do you mean the “explain” command?

**Comment by hiberabyss** [comment]
@c9s I mean the `kubectl exec` command.

**Comment by c9s** [comment]
Hi @hiberabyss , it's already supported. You may hit `x` and if the pod contains more than one containers, a list will be displayed, you can choose which container to connect.

**Comment by hiberabyss** [comment]
Cool !
