### ISSUE TITLE
Open VikubeExplorer with resource type

### ISSUE THREAD

**Issue by doggy8088** [c9s/vikube.vim#13]
Can you provide some usage examples for `:Vikube [ResourceType]`?  I don't know how to open specific type using `:Vikube [ResourceType]` command.  Here are my attempts that failed:

* `:Vikube service`
  * Result: `E488: Trailing characters`
* `:Vikube svc`
  * Result: `E488: Trailing characters`
* `:Vikube "svc"` o `:Vikube "service"`
  * Result: Still open the default resource type: `Pod`

**Comment by c9s** [comment]
You can use “r” to look up resouces

And “?” To show the usage

Will 保哥 <notifications@github.com>於 2018年6月14日 週四，16:14寫道：

**Comment by doggy8088** [comment]
Got it.  Thanks! 👍

**Comment by c9s** [comment]
This is fixed, you can now use `:Vikube pods`, completion is now enabled.

**Comment by doggy8088** [comment]
@c9s I tried.  No working.

Here are my steps:

1. `vim +PluginInstall +qall`
2. `vim -c ":Vikube pod"`

I also tried:

1. `vim`
2. `:Vikube pod`
Then I still got `E488: Trailing characters` response.

Do I misunderstanding something?
