### ISSUE TITLE
Blanking issue in VikubeExplorer

### ISSUE THREAD

**Issue by doggy8088** [c9s/vikube.vim#14]
Here is a tiny UX issue that is when I enabled `let g:vikube_autoupdate = 1`, the screen will be blanking all the time.  Is this possibly to get fixed?

![image](https://i.imgur.com/wfdESsm.gif)

**Comment by c9s** [comment]
Thanks! Looks like a bug, i will fix it soon

Will 保哥 <notifications@github.com>於 2018年6月14日 週四，17:47寫道：

**Comment by c9s** [comment]
Thanks! this is now fixed, please pull down the latest master
