### ISSUE TITLE
An error occurred while starting Vikube on Kubernetes v1.11

### ISSUE THREAD

**Issue by kairen** [c9s/vikube.vim#17]
#### What happened:
Starting Vikube with `vim +Vikube` or `:Vikube` command will be failed.

#### How to reproduce it:
Install the latest commit of Vikube version, and then launch it.

#### Environment:
* OS : Ubuntu 16.04 and Mac OS X 
* Kubernetes: v1.11.0
* kubectl: v1.11.0
* Commit hash: 1343b61709b986c572c24ce80a864ae46fce242c.

For more details, please refer to the record:

[![asciicast](https://asciinema.org/a/lex4n7mv5Rcf9gfdm5mHXEMAL.png)](https://asciinema.org/a/lex4n7mv5Rcf9gfdm5mHXEMAL)

**Comment by c9s** [comment]
Can you “get pods”? Or did you change the default resource type?

**Comment by c9s** [comment]
Does this still happen?

**Comment by c9s** [comment]
The command parsing part was re-written. Please re-open this issue if it still exists.
