### ISSUE TITLE
[Feature Request] Unset default bindings

### ISSUE THREAD

**Issue by dv-blk** [c9s/vikube.vim#18]
A disable default bindings config variable would be nice, thanks!

For now i'm just deleting `/after/plugin/mapping.vim` as a workaround

**Comment by c9s** [comment]
done in commit 9030e8efa81018dd1061b8b8e387b2f4e6a742ea

**Comment by c9s** [comment]
you can define:

    let g:vikube_default_mapping = 0

in your .vimrc

**Comment by dv-blk** [comment]
woot!
