### ISSUE TITLE
Research should be persistent

### ISSUE THREAD

**Issue by valentin2105** [c9s/vikube.vim#5]
Hi, 

I'm not able to make a PR for that, 

But when you search with "/string", it filters pod with a nice way, but, It's not possible to "keep" this filtered search. You know what I would say ? 

It would be great to be able to navigate in the filtered search. 

Not any idea how to do that 🤣

**Comment by c9s** [comment]
Sure, I can add this behavior

**Comment by c9s** [comment]
I just fixed this issue , please update and take a look
